import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import "./globals.css";

const neueMontreal = localFont({
  src: [
    { path: "../public/fonts/neue-montreal/NeueMontreal-Light.otf", weight: "300", style: "normal" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-LightItalic.otf", weight: "300", style: "italic" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-Regular.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-Italic.otf", weight: "400", style: "italic" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-Medium.otf", weight: "500", style: "normal" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-MediumItalic.otf", weight: "500", style: "italic" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-Bold.otf", weight: "700", style: "normal" },
    { path: "../public/fonts/neue-montreal/NeueMontreal-BoldItalic.otf", weight: "700", style: "italic" },
  ],
  variable: "--font-neue-montreal",
});

const tiemposFine = localFont({
  src: [
    { path: "../public/fonts/tiempos/TestTiemposFine-Light-BF66457a5102792.otf", weight: "300", style: "normal" },
    { path: "../public/fonts/tiempos/TestTiemposFine-LightItalic-BF66457a50eb132.otf", weight: "300", style: "italic" },
    { path: "../public/fonts/tiempos/TestTiemposFine-Regular-BF66457a50e8bc9.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/tiempos/TestTiemposFine-RegularItalic-BF66457a50e36f9.otf", weight: "400", style: "italic" },
    { path: "../public/fonts/tiempos/TestTiemposFine-Medium-BF66457a50e62cd.otf", weight: "500", style: "normal" },
    { path: "../public/fonts/tiempos/TestTiemposFine-MediumItalic-BF66457a511be83.otf", weight: "500", style: "italic" },
    { path: "../public/fonts/tiempos/TestTiemposFine-Semibold-BF66457a50f016a.otf", weight: "600", style: "normal" },
    { path: "../public/fonts/tiempos/TestTiemposFine-SemiboldItalic-BF66457a50b0e18.otf", weight: "600", style: "italic" },
    { path: "../public/fonts/tiempos/TestTiemposFine-Bold-BF66457a510211b.otf", weight: "700", style: "normal" },
    { path: "../public/fonts/tiempos/TestTiemposFine-BoldItalic-BF66457a50b8568.otf", weight: "700", style: "italic" },
    { path: "../public/fonts/tiempos/TestTiemposFine-Black-BF66457a508fe8f.otf", weight: "900", style: "normal" },
    { path: "../public/fonts/tiempos/TestTiemposFine-BlackItalic-BF66457a510424a.otf", weight: "900", style: "italic" },
  ],
  variable: "--font-test-tiempos-fine",
});

const archivoBlack = localFont({
  src: [
    { path: "../public/fonts/archivo-black/ArchivoBlack-Regular.ttf", weight: "400", style: "normal" },
  ],
  variable: "--font-archivo-black",
});

const spaceMono = localFont({
  src: [
    { path: "../public/fonts/space-mono/SpaceMono-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/space-mono/SpaceMono-Italic.ttf", weight: "400", style: "italic" },
    { path: "../public/fonts/space-mono/SpaceMono-Bold.ttf", weight: "700", style: "normal" },
    { path: "../public/fonts/space-mono/SpaceMono-BoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "ASG - Amanat Shah Group",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        {/* Preload splash logo so it's decoded before the animation starts */}
        <link rel="preload" as="image" href="/logo/ASG-logo.png" />
      </head>
      <body className={`${neueMontreal.variable} ${tiemposFine.variable} ${archivoBlack.variable} ${spaceMono.variable} min-h-screen flex flex-col font-neue-montreal`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
