import type { Metadata } from "next";
import Header from "@/components/layout/header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "ASG - Amanat Shah Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/pp-neue-montreal"
          rel="stylesheet"
        />
        <link
          href="https://cdn.msar.me/fonts/Tiempos/font.css"
          rel="stylesheet"
        />
      </head>
      <body className="h-screen min-h-full flex flex-col font-neue-montreal bg-blue-500">
        <Header />
        {children}
      </body>
    </html>
  );
}
